<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP9hgo40\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP9hgo40/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP9hgo40.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP9hgo40\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerP9hgo40\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'P9hgo40',
    'container.build_id' => '379a688f',
    'container.build_time' => 1554734924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP9hgo40');
