<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV5NFbx8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV5NFbx8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV5NFbx8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV5NFbx8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerV5NFbx8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'V5NFbx8',
    'container.build_id' => '6a8ccb06',
    'container.build_time' => 1554733478,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV5NFbx8');
